server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
    globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:5173" # Dirección del frontend (React)
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*" # Permite todos los encabezados
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: register-service
          uri: lb://register-service
          predicates:
            - Path=/register/**
            
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loans/**

        - id: document-service
          uri: lb://loan-service
          predicates:
            - Path=/documents/**
            
        - id: simulate-service
          uri: lb://simulate-service
          predicates:
            - Path=/simulate/**
            
        - id: evaluation-service
          uri: lb://evaluation-service
          predicates:
            - Path=/evaluate/**
            
        - id: followup-service
          uri: lb://followup-service
          predicates:
            - Path=/followup/**
