server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
            
        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/document/**
            
        - id: simulate-service
          uri: lb://simulate-service
          predicates:
            - Path=/simulate/**
